/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fd1184dc-4e19-4377-8ef2-4c5948abfb2f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_olQSZVSUA",
    "aws_user_pools_web_client_id": "5udfkgg0a5tpjfb784j3d3g6ef",
    "oauth": {},
    "aws_cognito_login_mechanism": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 7,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://g5d4pz4oqff4zef6mwx3e4j4ea.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tye56mvosjb3pokiaxoz3i4eja"
};


export default awsmobile;
